name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        shell: bash

      - name: Checkout submodules
        run: git submodule update --init --recursive
        shell: bash

      - name: Download app deps
        run: ./gradlew androidDependencies
        shell: bash

      - name: Build
        run: ./gradlew clean assembleDebug
        shell: bash

      - name: Sign debug APK
        run: |
          apksigner="$(find $ANDROID_SDK_ROOT/build-tools -name apksigner | sort -r | head -n 1)"
          "$apksigner" sign --ks public.jks --ks-key-alias public --ks-pass pass:public --key-pass pass:public --in ./app/build/outputs/apk/arch_arm/debug/app-arch_arm-debug.apk --out ./app-arch_arm-debug-signed.apk
          "$apksigner" sign --ks public.jks --ks-key-alias public --ks-pass pass:public --key-pass pass:public --in ./app/build/outputs/apk/arch_arm64/debug/app-arch_arm64-debug.apk --out ./app-arch_arm64-debug-signed.apk
        shell: bash

      - name: Upload arm apk
        uses: actions/upload-artifact@v3
        with:
          name: app-arch_arm-debug-signed
          path: ./app-arch_arm-debug-signed.apk
          if-no-files-found: error

      - name: Upload arm64 apk
        uses: actions/upload-artifact@v3
        with:
          name: app-arch_arm64-debug-signed
          path: ./app-arch_arm64-debug-signed.apk
          if-no-files-found: error


